export const sampleData = [
  {
    poNumber: 'Localize_Merril_201909_12345',
    createdOn: '09/04/2019',
    projectName: 'Insurance Related Project',
    localizePM: 'Apurva',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'mary@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_EDU_201909_99999',
    createdOn: '09/04/2019',
    projectName: 'Education Related Project',
    localizePM: 'Gaurav',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'vendor@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_Merril_201909_12345',
    createdOn: '09/04/2019',
    projectName: 'Insurance Related Project',
    localizePM: 'Apurva',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'mary@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_EDU_201909_99999',
    createdOn: '09/04/2019',
    projectName: 'Education Related Project',
    localizePM: 'Gaurav',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'vendor@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_Merril_201909_12345',
    createdOn: '09/04/2019',
    projectName: 'Insurance Related Project',
    localizePM: 'Apurva',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'mary@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_EDU_201909_99999',
    createdOn: '09/04/2019',
    projectName: 'Education Related Project',
    localizePM: 'Gaurav',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'vendor@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_Merril_201909_12345',
    createdOn: '09/04/2019',
    projectName: 'Insurance Related Project',
    localizePM: 'Apurva',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'mary@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_EDU_201909_99999',
    createdOn: '09/04/2019',
    projectName: 'Education Related Project',
    localizePM: 'Gaurav',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'vendor@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_Merril_201909_12345',
    createdOn: '09/04/2019',
    projectName: 'Insurance Related Project',
    localizePM: 'Apurva',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'mary@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  },
  {
    poNumber: 'Localize_EDU_201909_99999',
    createdOn: '09/04/2019',
    projectName: 'Education Related Project',
    localizePM: 'Gaurav',
    clientName: 'John Doe',
    clientPM: 'John Doe PM',
    vendorName: 'Mary Doe',
    vendorMailId: 'vendor@vendor.com',
    workType: 1,
    language: 'English',
    wordCount: 500,
    vendorCost: 4000,
    currency: 1,
    createdBy: 'apurav@localize.com',
    systemCreatedOn: new Date(),
    modifiedOn: new Date()
  }
]