export const CREATE_UPDATE_REQUEST = 'EVENT_UPSERT_REQUEST';
export const CREATE_UPDATE_SUCCESS = 'EVENT_UPSERT_SUCCESS';
export const CREATE_UPDATE_FAILURE = 'EVENT_UPSERT_FAILURE';

export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST';
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS';
export const ALL_EVENTS_FAILURE = 'ALL_EVENTS_FAILURE';

export const EVENT_COUNT_REQUEST = 'EVENT_COUNT_REQUEST';
export const EVENT_COUNT_SUCCESS = 'EVENT_COUNT_SUCCESS';
export const EVENT_COUNT_FAILURE = 'EVENT_COUNT_FAILURE';

export const ALL_EVENT_REQUEST = 'ALL_EVENT_REQUEST';
export const ALL_EVENT_SUCCESS = 'ALL_EVENT_SUCCESS';
export const ALL_EVENT_FAILURE = 'ALL_EVENT_FAILURE';

export const EDIT_ADMIN_EVENT = 'EDIT_ADMIN_EVENT';
