export const CREATE_UPDATE_REQUEST = 'PO_UPSERT_REQUEST';
export const CREATE_UPDATE_SUCCESS = 'PO_UPSERT_SUCCESS';
export const CREATE_UPDATE_FAILURE = 'PO_UPSERT_FAILURE';

export const ALL_POS_REQUEST = 'ALL_POS_REQUEST';
export const ALL_POS_SUCCESS = 'ALL_POS_SUCCESS';
export const ALL_POS_FAILURE = 'ALL_POS_FAILURE';
